weapons={
None:{"name":"无","value":5,"count":"0","distance":1},
"测试-伤害10":{"name":"测试1","value":"10","count":"0","distance":3},
"测试-伤害15":{"name":"测试2","value":"15","count":"0","distance":5},
"屠龙宝刀":{"name":"屠龙宝刀1","value":"1000","count":"0","distance":100}
    }
shields={
None:{"name":"无","value":0,"count":"0"},
"测试-防御1":{"name":"测试1","value":1,"count":"0"},
"测试-防御3":{"name":"测试2","value":3,"count":"0"}
    }
shoes={
None:{"name":"无","value":0,"count":"0"},
"测试-加速1":{"name":"测试1","value":1,"count":"0"},
"测试-加速3":{"name":"测试2","value":3,"count":"0"},
    }
