name: 使用PyInstaller自动打包

on:
  push:
    branches:
      - gui

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 拉取代码
      uses: actions/checkout@v2
      with:
        ref: gui

    - name: 搭建 Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: 生成cache_sum_code.py
      run: |
        cd src
        python main.py --genonly

    - name: 复制文件
      run: |
        cp ./packer_tmp.py ./src/packer_tmp.py
        cp ./game.exe.spec ./src/game.exe.spec
        cp ./requirements.txt ./src/requirements.txt

    - name: 运行PyInstaller
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: game.exe.spec
        requirements: requirements.txt

    - name: 移出game.exe
      run: |
        cp src/dist/windows/game.exe ./src/game.exe

    - name: 压缩
      run: |
        cd src
        zip -r build.zip resources config.py.txt game.exe

    - name: 上传附件
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          src/resources
          src/config.py.txt
          src/game.exe
        retention-days: 10
    
    - name: 删除旧Release
      uses: larryjoelane/delete-release-action@v1.0.24
      with: 
        release-name: auto-release
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: 上传Release
      uses: softprops/action-gh-release@v1
      with:
        files: src/build.zip
        tag_name: auto-release
        name: 自动构建
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
